### PR TITLE
added transistions

### PR DESCRIPTION
**Pull request by joshafest**
This can be fearther improved,
the minimum api should be changed to 21

### CODE REVIEW

**Comment by joshafest** [comment]
any reason to close it?

**Comment by sukhbir-singh** [comment]
This transition is not looking good in app, try other transition....

**Comment by joshafest** [comment]
ok, and nimbus transitions are good ?

these type of transitions are said to be the best by android developer, ofcourse it is not because you don't like them.
Moerover the app is heavy you need to use convensional methods.

i can change base code if you like.

**Comment by joshafest** [comment]
also if you need these transitions at lower api s i can tweak android library and it can also work on lower android.

**Pull request closed without merging**
